04-2
js-tasks-ru/vue-20220419_tickets pull request #8
Opened 2022-05-11 08:28 UTC by MichZakh

2022-05-11 10:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-11 14:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-12 05:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-13 09:29 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-05-13 09:29 UTC, MichZakh commented
Приветствую!
У меня вопрос: Необходимо-ли как-то чистить запущенные таймеры или они удаляются, когда объект Тост перестает отображаться в приложении? 
Спасибо!

2022-05-13 15:21 UTC, ShGKme requested changes
В 04-vue-cli/02-TheToaster требуется не использовать время в качестве идентификатора...
также желательно немного поправить интерфейс компонента, и использовать для определения типа не класс из вёрстки, а сам тип, позже вычисляя класс. Так вёрстка не будет протекать в использование компонента.

UiDropdown - принята.

2022-05-13 15:21 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Методы получились довольно большими, но почти не отличаются. Лучше сделать какой-то "универсальный" метод и вызывать его из этих двух.

2022-05-13 15:21 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Лучше не использовать время (`new Date().getTime()`) в качестве идентификатора. Не гарантируется его уникальность. Вместо времени может быть инкрементный идентификатор (просто делать `lastId++` на уровне модуля компонента), или случайный (`nanoid`, `uuid`).

2022-05-13 15:21 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Сейчас в качестве типа тоста (type) используется имя класса этого тоста. При этом сами классы в вёрстке описаны в другом компоненте - в `UiToast`. Так использовать UiToast не очень удобно, значения его параметров завязываются на его вёрстке. Лучше оставлять тип менее привязанным к вёрстке, а уже класс в реализации придумывать в соответствии с типом, либо иметь объект соответствия, как вы сделали с иконкой.

2022-05-13 15:21 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    },
Этот параметр не используется, иконка вычисляется в вычисляемом свойстве на основе типа, что на мой взгляд как раз более корректное решение.

2022-05-13 15:21 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Здесь хорошо подходит метод `some`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2022-05-13 15:22 UTC, ShGKme commented
> Приветствую!
> У меня вопрос: Необходимо-ли как-то чистить запущенные таймеры или они удаляются, когда объект Тост перестает > отображаться в приложении?
> Спасибо!

Да, желательно чистить. Для этого их нужно где-то хранить и в хуке жизненного цикла `beforeUnmount` или `unmounted`  чистить все запущенные таймеры. Хотя в этом компоненте это маловероятно приведёт к проблеме, так как тостер обычно не исчезает.

2022-05-16 08:42 UTC, MichZakh commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Все поправил!

2022-05-16 08:42 UTC, MichZakh commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    },
Все поправил!

2022-05-16 08:46 UTC, MichZakh commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Все поправил!

2022-05-16 08:47 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-05-16 11:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-05-16 15:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-05-16 16:51 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-05-16 16:52 UTC, merged